### ISSUE TITLE
Vue Router warn

### ISSUE THREAD

**Issue by GoldraK** [fsgreco/vue3-laravel-api#1]
Hello,
  I have tested the code to be able to integrate with my laravel api and it works perfectly, but when reviewing it I have seen the following warn.

![imagen](https://user-images.githubusercontent.com/1814307/198524523-b6fb9003-8091-467f-9a0b-52521f044b0e.png)

If you change [this if ](https://github.com/fsgreco/vue3-laravel-api/blob/main/src/router/middleware/auth-middleware.js#L13)

for this

```js
if (isGoingExceptionalRoutes) {
	next() // The user is not logged in but it's going to exceptional routes ? fine
	return
} else {
	next({ name: 'login' })
	return
} // other routes than exceptional paths => /login
```

**Comment by fsgreco** [comment]
Thank you so much for this, I will test it as soon as I have a moment to do it and if everything seems ok I'll merge your pull request :)

I was convinced that `next()` performs a `return` but apparently it doesn't.
